version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: infotc4320-final
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            FLASK_DEBUG: "1"